# **Colab Notebooks**

To run this tutorial entirely in Colab, click the Open in Colab badge at the very top of this page. Sign in with your google account and click on the '[ ]' sign at top of each code cell to run the code of that cell.

# **Python**
Python is a high-level, dynamically typed multiparadigm programming language. Python code is often said to be almost like pseudocode, since it allows you to express very powerful ideas in very few lines of code while being very readable.

## if ... elif ... else

In [1]:
n = 3;
if n >= 1 and n < 5:  
  x = 1
elif n != 0:
  x = 1
else: 
  x = 0

## Loops
We can loop over the elements of a list like this:

In [2]:
for i in range(10):
  print(i, end=' ')

print()

animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal, end=' ')

print()

nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)   # Prints [0, 1, 4, 9, 16]

0 1 2 3 4 5 6 7 8 9
cat dog monkey
[0, 1, 4, 9, 16]

If you want access to the index of each element within the body of a loop, use the built-in enumerate function:

In [3]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print(f'#{idx + 1}: {animal}')

#1: cat
#2: dog
#3: monkey

## Functions
Python functions are defined using the `def` keyword. For example:

In [4]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

print(sign(-1))
print(sign(0))
print(sign(1))

negative
zero
positive

We will often define functions to take optional keyword arguments, like this:

In [5]:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)

hello('Bob') # Prints "Hello, Bob"
hello('Fred', loud=True)  # Prints "HELLO, FRED!"

Hello, Bob
HELLO, FRED!

In [6]:
def sumdiff(x,y):
    a = x + y;
    b = x - y;

    return a, b

sum, diff = sumdiff(5, 3)
print(sum, diff)

8 2

# **Numpy**
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. To start working with numpy we always need to import the numpy package. Run the cell below to import numpy.

In [7]:
import numpy as np

## Array
NumPyâ€™s array class is called ndarray. We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [8]:
a = np.array([2, 3, 4])   # Create array(1D) from python list
print(a[0])               # Access elements using square brackets

a[0] = 1                  # Change an element of the array
print(a)                  # Prints "[1, 3, 4]"


b = np.array([[2, 3, 4], [5, 6, 7]])  # Create a 2D array
print(b[0, 1])                        # Prints 3

b[1, 1] = 1                           # Change an element of the array
print(b[0, 0], b[0, 1], b[1, 0])      # Prints "2 3 5"

c = np.array([(1.5, 2, 3), (4, 5, 6)])# Create a 2D float array
print(c[0, 1])                        # Prints "2.0"

2
[1 3 4]
3
2 3 5
2.0

Some important attributes of an ndarray object are:


*   **ndarray.ndim:** the number of axes (dimensions) of the array.
*   **ndarray.shape:** the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.
*   **ndarray.size:** the total number of elements of the array. This is equal to the product of the elements of shape.
*   **ndarray.dtype:** an object describing the type of the elements in the array. numpy.int32, numpy.int16, and numpy.float64 are some examples.

In [9]:
print(a.ndim)             # Prints "1"
print(b.ndim)             # Prints "2"

print(a.shape)            # Prints "(3,)"
print(b.shape)            # Prints "(2, 3)"

print(a.size)             # Prints "3"
print(b.size)             # Prints "6"

print(a.dtype)            # Prints "int64"
print(c.dtype)            # Prints "float64"

1
2
(3,)
(2, 3)
3
6
int64
float64

Numpy also provides many functions to create arrays:

In [10]:
a = np.zeros((2,2))      # Create an array of all zeros
print(a)                 # Prints "[[ 0.  0.]
                         #          [ 0.  0.]]"

b = np.ones((1,2))       # Create an array of all ones
print(b)                 # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)    # Create a constant array
print(c)                 # Prints "[[ 7.  7.]
                         #          [ 7.  7.]]"

d = np.eye(2)            # Create a 2x2 identity matrix
print(d)                 # Prints "[[ 1.  0.]
                         #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

f = np.arange(3)         # Create an array filed with 0 to 2
print(f)                 # Prints "[0 1 2]"

g = np.linspace(2, 10, 5)    # Return evenly spaced 5 numbers over interval 2-10
print(g)                     # Prints [ 2.  4.  6.  8. 10.]

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.35504467 0.96818851]
 [0.3152296  0.78527069]]
[0 1 2]
[ 2.  4.  6.  8. 10.]

## Array indexing, Slicing and Iterating
One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [11]:
a = np.arange(10)**3     # In python "**" means power x**3 = x^3
print(a)                 # Prints "[0 1 8 27 64 125 216 343 512 729]"

print(a[2])              # Prints "8"
print(a[2:5])            # Prints "[8 27 64]"
print(a[:6])             # Prints "[0 1 8 27 64 125]"
print(a[2:])             # Prints "[8 27 64 125 216 343 512 729]"
print(a[::-1])           # Prints reversed array

a[:6:2] = 1000           # From start to position 6 (exclusive) set every 2nd element to 1000
print(a)                 # Prints "[1000 1 1000 27 1000 125 216 343 512 729]"

# Iterating over array
for element in a:
  print(element**(1/3.))

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[  0   1   8  27  64 125]
[  8  27  64 125 216 343 512 729]
[729 512 343 216 125  64  27   8   1   0]
[1000    1 1000   27 1000  125  216  343  512  729]
9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998

Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [12]:
b = np.array([[ 0,  1,  2,  3],
              [10, 11, 12, 13],
              [20, 21, 22, 23],
              [30, 31, 32, 33],
              [40, 41, 42, 43]])

print(b[2, 3])           # Prints "23"

print(b[:, 1])           # Print second column of b
print(b[:, 1:3])         # Print second and third column of b
print(b[:2, 2])          # Print first 2 rows in the third column of b
print(b[-2:, 1])         # Print last 2 rows in the second column of b
print(b[1:4, 2])         # Print rows 2-4 in the third column of b

print()

print(b[3, :])           # Print fourth row of b
print(b[1:3, :])         # Print second and third row of b
print(b[2, :2])          # Print first 2 columns in the third row of b
print(b[1, -2:])         # Print last 2 columns in the second row of b
print(b[2, 1:4])         # Print columns 2-4 in the third row of b

# Iterating over 2D array
for row in b:
  for col in row:
    print(col, end=' ')
  print()

23
[ 1 11 21 31 41]
[[ 1  2]
 [11 12]
 [21 22]
 [31 32]
 [41 42]]
[ 2 12]
[31 41]
[12 22 32]

[30 31 32 33]
[[10 11 12 13]
 [20 21 22 23]]
[20 21]
[12 13]
[21 22 23]
0 1 2 3
10 11 12 13
20 21 22 23
30 31 32 33
40 41 42 43

**Integer array indexing:** When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [13]:
a = np.array([[1,2], [3, 4], [5, 6]])

print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]

One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [14]:
a = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9], 
              [10, 11, 12]])

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[1  6  7 11]"

# Mutate one element from each row of a using the indices in b
# a += 1 equivalent to a = a + 1
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]

**Boolean array indexing:** Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [15]:
a = np.array([[1,2], 
              [3, 4], 
              [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])   # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])      # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]

## Changing the shape of an array

In [16]:
a = np.floor(10 * np.random.random((3, 4)))
print(a)

print(a.ravel())      # prints the array, flattened
print(a.reshape(6, 2))# prints the array with a modified shape

[[8. 3. 8. 6.]
 [0. 1. 3. 3.]
 [5. 9. 4. 4.]]
[8. 3. 8. 6. 0. 1. 3. 3. 5. 9. 4. 4.]
[[8. 3.]
 [8. 6.]
 [0. 1.]
 [3. 3.]
 [5. 9.]
 [4. 4.]]

## Stacking together different arrays
Several arrays can be stacked together along different axes:

In [17]:
# Create two random integer array
# elements are in range of 1 to 10
a = np.random.randint(low=1, high=10, size=(2,2))
b = np.random.randint(low=1, high=10, size=(2,2))

c = np.vstack((a, b))       # Vertically stack a and b
print(c)                    # Will print vertically stacked array

d = np.hstack((a, b))       # Horizontally stack a and b
print(d)                    # Will print horizontally stacked array

[[1 1]
 [3 8]
 [4 8]
 [3 1]]
[[1 1 4 8]
 [3 8 3 1]]

The function **column_stack** stacks 1D arrays as columns into a 2D array. It is equivalent to **hstack** only for 2D arrays:

In [18]:
# For 2D array
a = np.random.randint(low=1, high=10, size=(2,2))
b = np.random.randint(low=1, high=10, size=(2,2))

c = np.column_stack((a, b))
print(c)                     # Will print horizontally stacked array

# For 1D array
a = np.array([4., 2.])
b = np.array([3., 8.])

c = np.column_stack((a, b))  # returns a 2D array
print(c)                     # Prints [[4. 3.]
                             #         [2. 8.]]

[[3 2 3 3]
 [1 1 8 8]]
[[4. 3.]
 [2. 8.]]

On the other hand, the function **row_stack** is equivalent to **vstack** for any input arrays.

In [19]:
a = np.array([4., 2.])
b = np.array([3., 8.])

c = np.row_stack((a, b))     # returns a 2D array
print(c)                     # Prints [[4. 3.]
                             #         [2. 8.]]

[[4. 2.]
 [3. 8.]]

For higher dimentional array we can use **concatenate**. Here we need to pass an additional parameter name **axis**. **Concatenate** join a sequence of arrays along an existing axis. Insted of **vstack**, **hstack**, **column_stack** & **row_stack** we can always use **concatenate**.

In [20]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

c = np.concatenate((a, b), axis=0)   # Same as vstack
print(c)                             # Prints [[1 2]
                                     #         [3 4]
                                     #         [5 6]]   

d = np.concatenate((a, b.T), axis=1) # Same as hstack
print(d)                             # Prints [[1 2 5]
                                     #         [3 4 6]]

e = np.concatenate((a, b), axis=None)# Flatten the array
print(e)                             # Prints [1 2 3 4 5 6]

a = np.arange(3)                     # Creates array [0 1 2]
b = np.arange(2, 5)                  # Creates array [2 3 4]
f = np.concatenate([a, b])           # Concatenate
print(f)                             # Prints [0 1 2 2 3 4]

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[1 2 3 4 5 6]
[0 1 2 2 3 4]

## Basic Operations
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [21]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum
print(x + y)            # Operator overloading
print(np.add(x, y))     # Function in numpy module

# Elementwise difference
print(x - y)            # Operator overloading
print(np.subtract(x, y))# Function in numpy module

# Elementwise product
print(x * y)            # Operator overloading
print(np.multiply(x, y))# Function in numpy module

# Elementwise division
print(x / y)            # Operator overloading
print(np.divide(x, y))  # Function in numpy module

# Elementwise power
print(x**2)             # Operator overloading
print(np.power(x, 2))   # Function in numpy module

# Elementwise square root
print(x**(1/2.))        # Operator overloading
print(np.sqrt(x))       # Function in numpy module

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[ 1.  4.]
 [ 9. 16.]]
[[ 1.  4.]
 [ 9. 16.]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]

**Universal function:** NumPy provides familiar mathematical functions such as sin, cos, and exp.

In [22]:
a = np.arange(3)
print(np.exp(a))       # Exponential

print(np.sin(a))       # Sine

print(np.cos(a))       # Cosine

[1.         2.71828183 7.3890561 ]
[0.         0.84147098 0.90929743]
[ 1.          0.54030231 -0.41614684]

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [23]:
a = np.random.randint(10, size=(2, 4))
print(a)

print(a.sum())         # Prints the sum of all elements
print(a.min())         # Prints the minimum of all elements
print(a.max())         # Prints the maximum of all elements

[[2 5 3 3]
 [5 9 0 5]]
32
0
9

By specifying the axis parameter you can apply an operation along the specified axis of an array:

In [24]:
b = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

print(b.sum(axis=0))   # sum of each column
print(b.min(axis=1))   # min of each row
print(b.cumsum(axis=1))# cumulative sum along each row

[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]

We use the `dot` function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. `dot` is available both as a function in the numpy module and as an instance method of array objects:

In [25]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the 1D array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the 2D array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]

To transpose a matrix, simply use the `T` attribute of an array object:

In [26]:
x = np.array([[1,2], [3,4]])
print(x)               # Prints "[[1 2]
                       #          [3 4]]"
print(x.T)             # Prints "[[1 3]
                       #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)               # Prints "[1 2 3]"
print(v.T)             # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]

# **Pillow**
Pillow is the friendly PIL fork, a Python Imaging Library. This library provides extensive file format support, an efficient internal representation, and fairly powerful image processing capabilities.

In [27]:
from PIL import Image
from IPython.display import display # Needed to display the image

##Image operations
Pillow provides functions to work with images. For example, it has functions to read images from disk and cnvert into numpy arrays, to write numpy arrays to disk as images, and to resize images. Here is a simple example that showcases these functions:

***Note:** Please upload the 'cat.jpg' file to colab from the sidebar before proceeding to next step.

![cat.jpg]()

In [28]:
img = Image.open('cat.jpg')   # Load image from disk
display(img)                  # Visualize the image
width, height = img.size      # Gives image dimension
print(width, height)

img_data = np.asarray(img)    # Convert image to np array
print(img_data.shape)         # The image has shape (340, 325, 3)

img = Image.fromarray(img_data, mode='RGB') # Convert np array to PIL image
display(img)

# RGB image to Grayscale
gray_img = img.convert(mode='L') # Mode 'L' is 8-bit pixels, black and white
display(gray_img)

gray_img = gray_img.resize((300, 300)) # Resize image
display(gray_img)
gray_img.save('gray_cat.jpg')          # Save image

FileNotFoundError: ignored

# **Matplotlib**
Matplotlib is a plotting library. In this section give a brief introduction to the matplotlib.pyplot module, which provides a plotting system. Import `matplotlib.pyplot` to start working with plots.

In [ ]:
import matplotlib.pyplot as plt

## Plotting
The most important function in matplotlib is `plot`, which allows you to plot 2D data. Here is a simple example:

In [ ]:
x = np.arange(start = 0, stop = 3 * np.pi, step = 0.1)
y = np.sin(x)

# Plot the points using matplotlib
plt.plot(x, y)
plt.show()  # You must call plt.show() to make graphics appear.

With just a little bit of extra work we can easily plot multiple lines at once, and add a title, legend, and axis labels:

In [ ]:
x = np.arange(start = 0, stop = 3 * np.pi, step = 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Plot the points using matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])
plt.show()

## Subplots
We can plot different things in the same figure using the `subplot` function. Here is an example:

In [ ]:
x = np.arange(start = 0, stop = 3 * np.pi, step = 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(x, y_sin)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

# Show the figure.
plt.show()

## Surface plot
We can plot 3D surface using `plot_surface` function. Here is an example:

In [ ]:
X = np.arange(-2, 2, 0.25)
Y = np.arange(-2, 2, 0.25)

X, Y = np.meshgrid(X, Y)   # carefully check what x and y are

Z = X*np.exp(-X**2-Y**2)  # what will be Z(1)

fig = plt.figure()
ax = plt.axes(projection='3d')

ax.plot_surface(X, Y, Z,cmap='viridis', edgecolor='none')
ax.set_title('Surface plot')
plt.show()